export const SELECT_UNIT = 'SELECT_UNIT';

export const GET_CURRENT_LOCATION_REQUEST = 'GET_CURRENT_LOCATION_REQUEST';
export const GET_CURRENT_LOCATION_SUCCESS = 'GET_CURRENT_LOCATION_SUCCESS';
export const GET_CURRENT_LOCATION_FAILURE = 'GET_CURRENT_LOCATION_FAILURE';

export const GET_LOCATION_FOR_ADDRESS_REQUEST = 'GET_LOCATION_FOR_ADDRESS_REQUEST';
export const GET_LOCATION_FOR_ADDRESS_SUCCESS = 'GET_LOCATION_FOR_ADDRESS_SUCCESS';
export const GET_LOCATION_FOR_ADDRESS_FAILURE = 'GET_LOCATION_FOR_ADDRESS_FAILURE';

export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE';
